# https://pypi.org/project/pysen/
# pysen run format && pysen run lint

[tool.pysen]
version = "0.10.1"

[tool.pysen.lint]
enable_black = true
enable_flake8 = true
enable_isort = true
enable_mypy = true
mypy_preset = "strict"
line_length = 80
py_version = "py36"
[tool.pysen.lint.source]
  exclude_globs = ["**/*sample/"]
[tool.pysen.lint.mypy_modules."pysen.scripts"]
  preset = "entry"
[[tool.pysen.lint.mypy_targets]]
  paths = ["src"]
  